name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 6' # every Saturday at 08:00 PST (16:00 UTC)

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-flake-lock

      - name: Pull nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Get current packages
        run: |
          nix eval --json .#nixosConfigurations.okabe-rintarou.config.environment.systemPackages \
          | jq -r '.[]' \
          | sed -E 's/^\/nix\/store\/[a-z0-9]{32}-//' \
          | sort > "$RUNNER_TEMP/pre-update.txt"

      - name: Update flake.lock
        run: nix flake update --commit-lock-file

      - name: Validate changes
        run: nix flake check

      - name: Get updated packages
        run: |
          nix eval --json .#nixosConfigurations.okabe-rintarou.config.environment.systemPackages \
          | jq -r '.[]' \
          | sed -E 's/^\/nix\/store\/[a-z0-9]{32}-//' \
          | sort > "$RUNNER_TEMP/post-update.txt"

      - name: Generate diff
        run: |
          echo "## Package Updates (okabe-rintarou)" > "$RUNNER_TEMP/pr_diff.md"
          echo '```diff' >> "$RUNNER_TEMP/pr_diff.md"
          # tail to skip the file header (+3 starts at line 3)
          diff -u "$RUNNER_TEMP/pre-update.txt" "$RUNNER_TEMP/post-update.txt" | tail -n +3 >> "$RUNNER_TEMP/pr_diff.md" || true
          echo '```' >> "$RUNNER_TEMP/pr_diff.md"

      - name: Push changes
        run: |
          git push origin update-flake-lock --force

      - name: Create pull request
        run: |
          # Combine diff and footer into the body file
          cat "$RUNNER_TEMP/pr_diff.md" > "$RUNNER_TEMP/pr_body.md"
          echo "" >> "$RUNNER_TEMP/pr_body.md"
          echo "This PR updates the Nix dependencies in flake.lock to their latest versions. [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})." >> "$RUNNER_TEMP/pr_body.md"

          gh pr create \
            --title "chore: update Nix dependencies" \
            --body-file "$RUNNER_TEMP/pr_body.md" \
            --head update-flake-lock \
            --base ${{ github.ref_name }} || true # ignore error if PR already exists
        env:
          GH_TOKEN: ${{ github.token }}
