name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 6' # every Saturday at 08:00 PST (16:00 UTC)

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-flake-lock

      - name: Pull nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update flake.lock
        run: nix flake update --commit-lock-file

      - name: Validate changes
        run: nix flake check

      - name: Push changes
        run: |
          git push origin update-flake-lock --force

      - name: Create pull request
        run: |
          gh pr create \
            --title "chore: update Nix dependencies" \
            --body "This PR updates the Nix dependencies in flake.lock to their latest versions. [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})." \
            --head update-flake-lock \
            --base ${{ github.ref_name }} || true # ignore error if PR already exists
        env:
          GH_TOKEN: ${{ github.token }}
